# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildnTest
  displayName: Build and Test the client image
  jobs:  
  - job: ClientTestBuild
    displayName: Build and test the client image
    steps:
    - script: |
       docker build -t vpraveenon/client-test -f client/Dockerfile.dev client/
       docker run -e CI=true vpraveenon/client-test npm run test -- --coverage 

